#!/usr/bin/env python3
"""Spectrum of the mastered score, 30 fps × 64 log bands, so the picture can
breathe with the real music (and the Fourier chapter can show its own FFT)."""
import os, base64, json
import numpy as np
from scipy.io import wavfile
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sr, x = wavfile.read(os.path.join(ROOT, "build", "score_master.wav"))
x = x.astype(np.float32) / 32768.0; m = x.mean(1)
FPS, NB, NFFT = 30, 64, 4096
frames = int(len(m) / sr * FPS)
edges = np.geomspace(40, 14000, NB + 1)
freqs = np.fft.rfftfreq(NFFT, 1 / sr)
win = np.hanning(NFFT).astype(np.float32)
band_idx = [np.where((freqs >= edges[i]) & (freqs < edges[i + 1]))[0] for i in range(NB)]
for i in range(NB):
    if len(band_idx[i]) == 0: band_idx[i] = np.array([np.argmin(np.abs(freqs - (edges[i] + edges[i + 1]) / 2))])
spec = np.zeros((frames, NB), np.float32); rms = np.zeros(frames, np.float32)
for f in range(frames):
    c = int(f / FPS * sr); seg = m[max(0, c - NFFT // 2): c + NFFT // 2]
    if len(seg) < NFFT: seg = np.pad(seg, (0, NFFT - len(seg)))
    P = np.abs(np.fft.rfft(seg * win)) ** 2
    spec[f] = [10 * np.log10(P[ix].mean() + 1e-12) for ix in band_idx]
    rms[f] = np.sqrt(np.mean(seg[NFFT // 4: 3 * NFFT // 4] ** 2))
tilt = np.linspace(0, 18, NB)                       # flatten the natural slope so highs read
spec = spec + tilt
lo, hi = np.percentile(spec, 8), np.percentile(spec, 99.7)
q = np.clip((spec - lo) / (hi - lo), 0, 1)
# light temporal smoothing (attack fast, release slow)
for f in range(1, frames): q[f] = np.maximum(q[f], q[f - 1] * 0.82)
e = rms / np.percentile(rms, 99.5); e = np.clip(e, 0, 1)
out = {"fps": FPS, "bands": NB, "frames": frames,
       "spec": base64.b64encode((q * 255).astype(np.uint8).tobytes()).decode(),
       "energy": base64.b64encode((e * 255).astype(np.uint8).tobytes()).decode()}
with open(os.path.join(ROOT, "src", "spectrum.js"), "w") as fo:
    fo.write("// generated by tools/analyze.py — 30 fps × 64-band spectrum + RMS of the mastered score\n")
    fo.write("window.SPECTRUM = " + json.dumps(out) + ";\n")
print("frames", frames, "size KB", os.path.getsize(os.path.join(ROOT, "src", "spectrum.js")) // 1024)
